POST http://localhost:8080/test
Content-Type: application/x-www-form-urlencoded

id=99&content=new-element

###

POST http://localhost:8080/get-by-id
Content-Type: application/x-www-form-urlencoded

id=99&content=new-element

###
GET http://localhost:8080/api
Accept: application/json

###

POST http://localhost:8080/hand
Accept: application/json

###